myAge=input()
print('You will be'+ str(int(myAge)+1)+' in the year')
print('you will be'+str(int('4')+1)+'in a year')
print('you will be'+str(4+1)+'in a year')
print('you will be'+str(5)+'in a year')
print('you will be'+'5'+'in a year')
print('you will be5'+ 'in a year')
print('you will be 5 in a year')