a=float(input('giá niêm yết'))
b=float(input('giá chiếc khấu'))
VAT=((a-b)*0.01)
print(a-b+VAT)
hovaten="nguyenthituyettrinh"
print("chao ban",str(hovaten))
a=float(input('nhap so a'))
b=float(input('nhap so b'))
c=float(input('nhap so c'))
d=float(input('nhap so d'))
print(a+b+c+d)
print((a+b+c+d)/4)