n=float(input('so tien ban dau n'))
k=float(input('so thang gui k'))
t=float(input('lai suat t'))
m=n*(1+k*t)
print('Voi so tien ban dau',n,',','sau',k,'thang gui',',','lai suat',t,'/','thang')
print('Thi so tien nhan duoc cuoi ky la:',m)
